from abc import ABC, abstractmethod


class ILogger(ABC):
    @abstractmethod
    def debug(self, msg: str) -> None: ...
    @abstractmethod
    def info(self, msg: str) -> None: ...
    @abstractmethod
    def warning(self, msg: str) -> None: ...
    @abstractmethod
    def error(self, msg: str) -> None: ...
