from abc import ABC, abstractmethod
from pathlib import Path


class ILogger(ABC):
    @abstractmethod
    def debug(self, msg: str) -> None: ...
    @abstractmethod
    def info(self, msg: str) -> None: ...
    @abstractmethod
    def warning(self, msg: str) -> None: ...
    @abstractmethod
    def error(self, msg: str) -> None: ...


class INotifier(ABC):
    @abstractmethod
    def send_message(self, message: str) -> None: ...
    @abstractmethod
    def send_alert(self, message: str) -> None: ...


class ITickerRepository(ABC):
    @abstractmethod
    def reset_schema(self) -> None: ...
    @abstractmethod
    def bulk_insert_from_xlsx_dir(self, data_dir: Path, filenames: list[str]) -> int: ...
    @abstractmethod
    def group_summary(self) -> list[tuple]: ...
    @abstractmethod
    def sample(self, limit: int = 5) -> list[tuple]: ...
